-- Adds a second Chart of Accounts seed template ("kl", named for the user's
-- own real-world COA structure from Kopitiam Lim) selectable at org
-- registration, alongside the existing hardcoded ~200-account default.
-- register_new_org gains an optional p_coa_template param (defaults to
-- 'default' so every existing call site is unaffected). Whichever seed
-- runs, repair_coa_hierarchy() (already called unconditionally afterward)
-- derives is_header/level/parent_id purely from each account's own code
-- structure, so it works identically for either template with no changes.
--
-- The KL template's default_coa_mappings only maps accounts_payable
-- (2-1-01-001, "AP - Raw Material & Supplies" — the KL structure's clear
-- equivalent); it has no dedicated Freight/PPN Masukan/PPN Keluaran
-- accounts, so those three roles are left unmapped for it, same tolerant
-- "genuinely optional, not a blocker" treatment the PPH roles already get
-- for the default template.

DROP FUNCTION IF EXISTS public.register_new_org(UUID, TEXT, TEXT, TEXT);

CREATE OR REPLACE FUNCTION public.register_new_org(
  p_user_id      UUID,
  p_full_name    TEXT,
  p_org_name     TEXT,
  p_outlet_name  TEXT,
  p_coa_template TEXT DEFAULT 'default'
)
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_org_id    UUID;
  v_outlet_id UUID;
BEGIN
  -- Guard: prevent duplicate profiles (idempotent on retry)
  IF EXISTS (SELECT 1 FROM user_profiles WHERE id = p_user_id) THEN
    SELECT org_id INTO v_org_id FROM user_profiles WHERE id = p_user_id;
    SELECT id    INTO v_outlet_id FROM outlets WHERE org_id = v_org_id LIMIT 1;
    RETURN json_build_object('org_id', v_org_id, 'outlet_id', v_outlet_id);
  END IF;

  -- 1. Create organization
  INSERT INTO organizations (name)
  VALUES (p_org_name)
  RETURNING id INTO v_org_id;

  -- 2. Create first outlet
  INSERT INTO outlets (org_id, name)
  VALUES (v_org_id, p_outlet_name)
  RETURNING id INTO v_outlet_id;

  -- 3. Create user profile linked to org + outlet
  INSERT INTO user_profiles (id, org_id, full_name, role, outlet_ids)
  VALUES (p_user_id, v_org_id, p_full_name, 'owner', ARRAY[v_outlet_id]);

  -- 4. Seed Chart of Accounts (template-dependent)
  IF p_coa_template = 'kl' THEN
    INSERT INTO chart_of_accounts (org_id, code, name, type) VALUES
    (v_org_id, '1-0-00-000', 'CURRENT ASSETS', 'asset'),
    (v_org_id, '1-1-00-000', 'CASH, BANK & OTHER', 'asset'),
    (v_org_id, '1-1-01-000', 'CASH', 'asset'),
    (v_org_id, '1-1-01-001', 'House Bank - General Cashier', 'asset'),
    (v_org_id, '1-1-01-002', 'Petty Cash', 'asset'),
    (v_org_id, '1-1-01-003', 'Cash Clearance', 'asset'),
    (v_org_id, '1-1-02-000', 'BANK', 'asset'),
    (v_org_id, '1-1-02-001', 'BANK BNI', 'asset'),
    (v_org_id, '1-1-02-002', 'BANK BCA 9998', 'asset'),
    (v_org_id, '1-1-02-003', 'BANK BCA PC', 'asset'),
    (v_org_id, '1-1-02-004', 'BANK Mandiri', 'asset'),
    (v_org_id, '1-2-00-000', 'ACCOUNT RECEIVABLE', 'asset'),
    (v_org_id, '1-2-01-000', 'B2B Clearance', 'asset'),
    (v_org_id, '1-2-01-001', 'B2B Food Receivables (Catering/Event)', 'asset'),
    (v_org_id, '1-2-01-002', 'B2B WIP Receivables', 'asset'),
    (v_org_id, '1-2-01-003', 'B2B Trimming / Spoil / Waste Receivables', 'asset'),
    (v_org_id, '1-2-02-000', 'CITY LEDGER', 'asset'),
    (v_org_id, '1-2-02-001', 'AR - Transfer bank', 'asset'),
    (v_org_id, '1-2-02-002', 'AR - QR BCA', 'asset'),
    (v_org_id, '1-2-02-003', 'AR - QR BNI', 'asset'),
    (v_org_id, '1-2-02-004', 'AR - QR ESB', 'asset'),
    (v_org_id, '1-2-02-005', 'AR - EDC BCA', 'asset'),
    (v_org_id, '1-2-02-006', 'AR - EDC BNI', 'asset'),
    (v_org_id, '1-2-02-007', 'AR - Go Food', 'asset'),
    (v_org_id, '1-2-02-008', 'AR - Grab Food', 'asset'),
    (v_org_id, '1-2-02-009', 'AR - Shoope Food', 'asset'),
    (v_org_id, '1-2-02-010', 'AR - Paxel Market', 'asset'),
    (v_org_id, '1-2-02-011', 'AR - Marketing Complimentary', 'asset'),
    (v_org_id, '1-2-02-012', 'AR - Officer Complimentary', 'asset'),
    (v_org_id, '1-2-02-013', 'AR - Other', 'asset'),
    (v_org_id, '1-2-03-000', 'OTHER RECEIVABLE', 'asset'),
    (v_org_id, '1-2-03-001', 'AR - Employe Loan', 'asset'),
    (v_org_id, '1-3-00-000', 'INVENTORIES', 'asset'),
    (v_org_id, '1-3-01-000', 'INV. STORAGE', 'asset'),
    (v_org_id, '1-3-01-001', 'Inv - ST Dry Goods', 'asset'),
    (v_org_id, '1-3-01-002', 'Inv - ST Dairy & Eggs', 'asset'),
    (v_org_id, '1-3-01-003', 'Inv - ST Sauce, Syrup & Condiment', 'asset'),
    (v_org_id, '1-3-01-004', 'Inv - ST Frozen Ingredients', 'asset'),
    (v_org_id, '1-3-01-005', 'Inv - ST RTD', 'asset'),
    (v_org_id, '1-3-01-006', 'Inv - ST KOH WIP', 'asset'),
    (v_org_id, '1-3-01-007', 'Inv - ST FOH WIP', 'asset'),
    (v_org_id, '1-3-01-008', 'Inv - ST Other', 'asset'),
    (v_org_id, '1-3-01-009', 'Inv - ST Protein', 'asset'),
    (v_org_id, '1-4-00-000', 'PREPAID EXPENSES', 'asset'),
    (v_org_id, '1-4-01-000', 'PREPAID EXPENSES (-)', 'asset'),
    (v_org_id, '1-4-01-001', 'Building & Fire Insurance', 'asset'),
    (v_org_id, '1-4-01-002', 'Payroll & Related Expenses (*)', 'asset'),
    (v_org_id, '1-4-01-003', 'System Subscribe', 'asset'),
    (v_org_id, '1-4-01-004', 'Equipment & Machine Insurance', 'asset'),
    (v_org_id, '1-4-01-005', 'Rent & Occupancy Expense', 'asset'),
    (v_org_id, '1-4-01-006', 'Consultant Fee', 'asset'),
    (v_org_id, '1-4-01-007', 'Prepaid Taxes (*)', 'asset'),
    (v_org_id, '1-4-01-008', 'Miscellaneous Prepaid Expenses', 'asset'),
    (v_org_id, '1-5-00-000', 'OTHERS CURRENT ASSETS', 'asset'),
    (v_org_id, '1-5-01-000', 'OTHERS CURRENT ASSETS (-)', 'asset'),
    (v_org_id, '1-5-01-001', 'Barter Agreement', 'asset'),
    (v_org_id, '1-5-01-002', 'Deposit on Event (*)', 'asset'),
    (v_org_id, '1-5-01-003', 'Deposit on Purchase Contract', 'asset'),
    (v_org_id, '1-5-01-004', 'Travelling Expenses - Advance', 'asset'),
    (v_org_id, '1-5-01-005', 'Current Assets - Other', 'asset'),
    (v_org_id, '1-6-00-000', 'FIXED ASSETS', 'asset'),
    (v_org_id, '1-6-01-000', 'LAND Asset', 'asset'),
    (v_org_id, '1-6-01-001', 'Land', 'asset'),
    (v_org_id, '1-6-02-000', 'BUILDING Assets', 'asset'),
    (v_org_id, '1-6-02-001', 'Building', 'asset'),
    (v_org_id, '1-6-02-002', 'Building Improvement', 'asset'),
    (v_org_id, '1-6-03-000', 'FURNITURE, FIXTURE & EQUIPMENT (FFE)', 'asset'),
    (v_org_id, '1-6-03-001', 'Furniture', 'asset'),
    (v_org_id, '1-6-03-002', 'Fixture', 'asset'),
    (v_org_id, '1-6-03-003', 'Equipment Gol I', 'asset'),
    (v_org_id, '1-6-03-004', 'Equipment Gol II', 'asset'),
    (v_org_id, '1-6-04-000', 'OPERATING UTENSIL & EQUIPMENT', 'asset'),
    (v_org_id, '1-6-04-001', 'Bar Utensil', 'asset'),
    (v_org_id, '1-6-04-002', 'Kitchen Tool & Utensil', 'asset'),
    (v_org_id, '1-6-04-003', 'FO Equipment & Utensil', 'asset'),
    (v_org_id, '1-6-04-004', 'Back Of Office Tool', 'asset'),
    (v_org_id, '1-6-04-005', 'Chinaware,Glassware,Silverware', 'asset'),
    (v_org_id, '1-6-04-006', 'Human Capital Item', 'asset'),
    (v_org_id, '1-6-04-007', 'Beginning Purchase', 'asset'),
    (v_org_id, '1-7-00-000', 'OTHER FIXED ASSETS', 'asset'),
    (v_org_id, '1-7-01-000', 'OTHER FIXED ASSETS :', 'asset'),
    (v_org_id, '1-7-01-001', 'Other Fixed Assets - Organization Cost / Goodwill (*)', 'asset'),
    (v_org_id, '1-7-01-002', 'Grand Opening Expenses', 'asset'),
    (v_org_id, '1-7-01-003', 'Other Fixed Assets - Pre Opening Expenses', 'asset'),
    (v_org_id, '1-7-01-004', 'Assests In Transit', 'asset'),
    (v_org_id, '2-0-00-000', 'LIABILITIES', 'liability'),
    (v_org_id, '2-1-00-000', 'CURRENT LIABILITIES', 'liability'),
    (v_org_id, '2-1-01-000', 'ACCOUNT PAYABLE', 'liability'),
    (v_org_id, '2-1-01-001', 'AP - Raw Material & Supplies', 'liability'),
    (v_org_id, '2-1-01-002', 'AP - Utility', 'liability'),
    (v_org_id, '2-1-01-003', 'AP - Suspense', 'liability'),
    (v_org_id, '2-1-01-004', 'AP - Other', 'liability'),
    (v_org_id, '2-1-02-000', 'TRADE TAXED', 'liability'),
    (v_org_id, '2-1-02-001', 'Tax - Pembangunan I (11%)', 'liability'),
    (v_org_id, '2-1-02-002', 'Tax - PPh 21', 'liability'),
    (v_org_id, '2-1-02-003', 'Tax - PPh 21 Kas Negara', 'liability'),
    (v_org_id, '2-1-03-000', 'TRADE OTHER', 'liability'),
    (v_org_id, '2-1-03-001', 'Service Charge (7%)', 'liability'),
    (v_org_id, '2-1-03-002', 'BPJS Ketenagakerjaan', 'liability'),
    (v_org_id, '2-1-03-003', 'BPJS Kesehatan', 'liability'),
    (v_org_id, '2-1-03-004', 'Consigment', 'liability'),
    (v_org_id, '2-1-03-005', 'Lost and Breakage Fund', 'liability'),
    (v_org_id, '2-1-03-006', 'Trade Other - Other', 'liability'),
    (v_org_id, '2-1-04-000', 'ACCRUED EXPENSES', 'liability'),
    (v_org_id, '2-1-04-001', 'A/E - Payroll & Related', 'liability'),
    (v_org_id, '2-2-00-000', 'LONG TERM LIABILITIES', 'liability'),
    (v_org_id, '2-2-01-000', 'SHORT TERM LIABILITIES', 'liability'),
    (v_org_id, '2-2-01-001', 'Bank Loan (Short Term)', 'liability'),
    (v_org_id, '2-2-01-002', 'Financial Institution (Non Bank) Loan (Short', 'liability'),
    (v_org_id, '2-2-01-003', 'Bank Loan (Long Term / Due in This Year)', 'liability'),
    (v_org_id, '2-2-01-004', 'Financial Institution Loan (Long Term / Due i', 'liability'),
    (v_org_id, '2-2-02-000', 'NOTES PAYABLE', 'liability'),
    (v_org_id, '2-2-02-001', 'Leasing Agreement', 'liability'),
    (v_org_id, '2-2-02-002', 'Promisory Not', 'liability'),
    (v_org_id, '2-2-02-003', 'Release Payment Account', 'liability'),
    (v_org_id, '2-2-03-000', 'LONG TERM LOAN', 'liability'),
    (v_org_id, '2-2-03-001', 'Bank Loan', 'liability'),
    (v_org_id, '2-2-03-002', 'Long Term Notes Payable', 'liability'),
    (v_org_id, '2-2-03-003', 'Long Term Loan - Other', 'liability'),
    (v_org_id, '3-0-00-000', 'CAPITAL', 'equity'),
    (v_org_id, '3-1-00-000', 'OTHER CAPITAL', 'equity'),
    (v_org_id, '3-1-01-000', 'Capital(-)', 'equity'),
    (v_org_id, '3-1-01-001', 'Capital Share', 'equity'),
    (v_org_id, '3-1-01-002', 'Retained Earning Beg. Year', 'equity'),
    (v_org_id, '3-1-01-003', 'Retained Earning', 'equity'),
    (v_org_id, '3-1-01-004', 'Retained Earning - TA', 'equity'),
    (v_org_id, '3-1-01-005', 'Profit & Loss Current Year', 'equity'),
    (v_org_id, '3-1-01-006', 'Paid Up Capital', 'equity'),
    (v_org_id, '3-1-01-007', 'Owner Withdrawal', 'equity'),
    (v_org_id, '3-1-01-008', 'Balance Forward', 'equity'),
    (v_org_id, '4-0-00-000', 'REVENUES', 'income'),
    (v_org_id, '4-1-01-000', 'FOOD & BEVERAGE REVENUE', 'income'),
    (v_org_id, '4-1-01-001', 'Food Revenue', 'income'),
    (v_org_id, '4-1-01-002', 'Beverage Revenue', 'income'),
    (v_org_id, '4-1-01-003', 'Traditional Cake, Bakery, Pastry & Lite Bite Revenue', 'income'),
    (v_org_id, '4-1-01-004', 'Other Revenue', 'income'),
    (v_org_id, '4-1-02-000', 'REVENUE FROM NON BUSINESS SALES', 'income'),
    (v_org_id, '4-1-02-001', 'Sales - Material', 'income'),
    (v_org_id, '4-1-02-002', 'Discount', 'income'),
    (v_org_id, '4-1-02-003', 'Bill Discount', 'income'),
    (v_org_id, '4-1-02-004', 'Food Revenue Discount', 'income'),
    (v_org_id, '4-1-02-005', 'Beverage Revenue Discount', 'income'),
    (v_org_id, '4-1-02-006', 'Service Charge', 'income'),
    (v_org_id, '4-1-02-007', 'Tax PB1', 'income'),
    (v_org_id, '4-1-02-008', 'Rounding GainST', 'income'),
    (v_org_id, '4-1-02-009', 'Other Discount', 'income'),
    (v_org_id, '4-1-02-010', 'Other Revenue From Non Business Sales', 'income'),
    (v_org_id, '5-0-00-000', 'COST OF GOODS SOLD', 'expense'),
    (v_org_id, '5-1-01-000', 'COGS FOOD', 'expense'),
    (v_org_id, '5-1-01-001', 'Cost of Food Raw Material', 'expense'),
    (v_org_id, '5-1-01-002', 'Cost of Food Spoil / Waste', 'expense'),
    (v_org_id, '5-1-01-003', 'Cost Of Fruit and Vegetable', 'expense'),
    (v_org_id, '5-2-01-000', 'COGS OF BEVERAGE', 'expense'),
    (v_org_id, '5-2-01-001', 'Cost of Bev Raw Material', 'expense'),
    (v_org_id, '5-2-01-002', 'Cost of Bev Fruit and Vegetable', 'expense'),
    (v_org_id, '5-2-01-003', 'Cost of Bev Spoil / Waste', 'expense'),
    (v_org_id, '5-3-01-000', 'COGS OTHER REVENUES', 'expense'),
    (v_org_id, '5-3-01-001', 'Cost of Other Revenue', 'expense'),
    (v_org_id, '6-0-00-000', 'OPERATING EXPENSES', 'expense'),
    (v_org_id, '6-1-01-000', 'SALARIES AND WAGES', 'expense'),
    (v_org_id, '6-1-01-001', 'KOH S&W', 'expense'),
    (v_org_id, '6-1-01-002', 'FOH S&W', 'expense'),
    (v_org_id, '6-1-01-003', 'Production S&W', 'expense'),
    (v_org_id, '6-1-01-004', 'BOH S&W', 'expense'),
    (v_org_id, '6-1-01-005', 'HQ S&W', 'expense'),
    (v_org_id, '6-2-01-000', 'SUPPLIES EXPENSES', 'expense'),
    (v_org_id, '6-2-01-001', 'Production Supplies', 'expense'),
    (v_org_id, '6-2-01-002', 'Chemical, Cleaning and Sanitation Supplies', 'expense'),
    (v_org_id, '6-2-01-003', 'Guest Supplies', 'expense'),
    (v_org_id, '6-2-01-005', 'Production Fuel', 'expense'),
    (v_org_id, '6-3-01-000', 'MARKETING EXPENSE', 'expense'),
    (v_org_id, '6-3-01-001', 'Marketing Production Expense', 'expense'),
    (v_org_id, '6-3-01-002', 'Marketing Complimentary Expense', 'expense'),
    (v_org_id, '6-3-01-003', 'Marketing Advertising Expense', 'expense'),
    (v_org_id, '6-3-01-004', 'Other Marketing Expense', 'expense'),
    (v_org_id, '6-4-01-000', 'GENERAL EXPENSE', 'expense'),
    (v_org_id, '6-4-01-001', 'Entertainment & Misc Expense', 'expense'),
    (v_org_id, '6-4-01-002', 'IT, System Subscribe & Software Expense', 'expense'),
    (v_org_id, '6-4-01-004', 'Communication and WIFI Expense', 'expense'),
    (v_org_id, '6-4-01-005', 'Research & Learning Development Expense', 'expense'),
    (v_org_id, '6-4-01-006', 'Transport & Travel Expense', 'expense'),
    (v_org_id, '6-4-01-007', 'Officer Complimentary Expense', 'expense'),
    (v_org_id, '6-4-01-008', 'Commision, Bank Charge & MDR Expense', 'expense'),
    (v_org_id, '6-4-01-009', 'Human Capital Expense', 'expense'),
    (v_org_id, '6-4-01-010', 'Other General Expense', 'expense'),
    (v_org_id, '6-5-01-000', 'PREMISES EXPENSE', 'expense'),
    (v_org_id, '6-5-01-001', 'Rent & Occupancy Expense', 'expense'),
    (v_org_id, '6-5-01-002', 'Repairs & Maintenance Expense', 'expense'),
    (v_org_id, '6-5-01-004', 'Cleaning, Sanitation, Security & Safety Expense', 'expense'),
    (v_org_id, '6-5-01-005', 'Electricity and Water', 'expense'),
    (v_org_id, '6-5-01-006', 'Building Tax, Other Tax, Fees & Insurance Expense', 'expense'),
    (v_org_id, '6-5-01-007', 'Outsourcing Expense', 'expense'),
    (v_org_id, '6-5-01-008', 'Other Premises Expense', 'expense'),
    (v_org_id, '7-0-00-000', 'FIXED CHARGE', 'expense'),
    (v_org_id, '7-1-01-000', 'DEPRECIATION EXPENSES', 'expense'),
    (v_org_id, '7-1-01-001', 'Building Assets DE', 'expense'),
    (v_org_id, '7-1-01-002', 'Furniture & Fixture Equipment  DE', 'expense'),
    (v_org_id, '7-1-01-003', 'Operating Utensil & Equipment  DE', 'expense'),
    (v_org_id, '7-1-01-004', 'Other DE', 'expense');
  ELSE
  INSERT INTO chart_of_accounts (org_id, code, name, type) VALUES
    (v_org_id, '1-0-00-000', 'CURRENT ASSETS', 'asset'),
    (v_org_id, '1-1-00-000', 'CASH, BANK & OTHER', 'asset'),
    (v_org_id, '1-1-10-000', 'CASH', 'asset'),
    (v_org_id, '1-1-10-010', 'House Bank - General Cashier', 'asset'),
    (v_org_id, '1-1-10-020', 'Petty Cash', 'asset'),
    (v_org_id, '1-1-10-030', 'Cash Clearance', 'asset'),
    (v_org_id, '1-1-10-040', 'Cash Outlet', 'asset'),
    (v_org_id, '1-1-20-000', 'BANK', 'asset'),
    (v_org_id, '1-1-20-010', 'BANK BCA', 'asset'),
    (v_org_id, '1-1-20-020', 'BANK BRI', 'asset'),
    (v_org_id, '1-1-20-030', 'BANK Mandiri', 'asset'),
    (v_org_id, '1-1-20-040', 'BANK BCA PC', 'asset'),
    (v_org_id, '1-2-00-000', 'ACCOUNT RECEIVABLE', 'asset'),
    (v_org_id, '1-2-10-000', 'CLEARANCE', 'asset'),
    (v_org_id, '1-2-10-010', 'AR Clearance', 'asset'),
    (v_org_id, '1-2-10-020', 'Guest Ledger', 'asset'),
    (v_org_id, '1-2-10-030', 'Down Payment', 'asset'),
    (v_org_id, '1-2-20-000', 'CITY LEDGER', 'asset'),
    (v_org_id, '1-2-20-010', 'AR - Credit Card', 'asset'),
    (v_org_id, '1-2-20-020', 'AR - Debit Card', 'asset'),
    (v_org_id, '1-2-20-030', 'AR - Transfer bank', 'asset'),
    (v_org_id, '1-2-20-040', 'AR - QR Mandiri', 'asset'),
    (v_org_id, '1-2-20-050', 'AR - EDC Mandiri', 'asset'),
    (v_org_id, '1-2-20-060', 'AR - Complimentary', 'asset'),
    (v_org_id, '1-2-20-070', 'AR - Other', 'asset'),
    (v_org_id, '1-2-30-000', 'OTHER RECEIVABLE', 'asset'),
    (v_org_id, '1-2-30-010', 'AR - Employe Loan', 'asset'),
    (v_org_id, '1-2-30-020', 'PPN Masukan (Input VAT)', 'asset'),
    (v_org_id, '1-3-00-000', 'INVENTORIES', 'asset'),
    (v_org_id, '1-3-10-000', 'INV. KOH RAW MATERIAL', 'asset'),
    (v_org_id, '1-3-10-010', 'Inv - KOH Perishable', 'asset'),
    (v_org_id, '1-3-10-020', 'Inv - KOH Dairy & Egg', 'asset'),
    (v_org_id, '1-3-10-030', 'Inv - KOH Dry Store', 'asset'),
    (v_org_id, '1-3-10-040', 'Inv - KOH Sauce, Syrup & Condiment', 'asset'),
    (v_org_id, '1-3-10-050', 'Inv - KOH Frozen', 'asset'),
    (v_org_id, '1-3-10-060', 'Inv - KOH Traditional Cake, Bakery, Pastry & Lite Bite', 'asset'),
    (v_org_id, '1-3-20-000', 'INV. KOH WORK IN PROCESS', 'asset'),
    (v_org_id, '1-3-20-010', 'Inv - KOH WIP', 'asset'),
    (v_org_id, '1-3-30-000', 'INV. FOH RAW MATERIAL', 'asset'),
    (v_org_id, '1-3-30-010', 'Inv - FOH Perishable', 'asset'),
    (v_org_id, '1-3-30-020', 'Inv - FOH Dairy & Egg', 'asset'),
    (v_org_id, '1-3-30-030', 'Inv - FOH Dry Store', 'asset'),
    (v_org_id, '1-3-30-040', 'Inv - FOH Sauce, Syrup & Condiment', 'asset'),
    (v_org_id, '1-3-40-000', 'INV. FOH RTD INVENTORIES', 'asset'),
    (v_org_id, '1-3-40-010', 'Inv - FOH RTD', 'asset'),
    (v_org_id, '1-3-50-000', 'INV. FOH WORK IN PROCESS', 'asset'),
    (v_org_id, '1-3-50-010', 'Inv - FOH WIP', 'asset'),
    (v_org_id, '1-3-60-000', 'INV. STORAGE', 'asset'),
    (v_org_id, '1-3-60-010', 'Inv - ST Dry Store', 'asset'),
    (v_org_id, '1-3-60-020', 'Inv - ST Sauce, Syrup & Condiment', 'asset'),
    (v_org_id, '1-3-60-030', 'Inv - ST Frozen', 'asset'),
    (v_org_id, '1-4-00-000', 'PREPAID EXPENSES', 'asset'),
    (v_org_id, '1-4-10-000', 'PREPAID EXPENSES (-)', 'asset'),
    (v_org_id, '1-4-10-010', 'Building & Fire Insurance', 'asset'),
    (v_org_id, '1-4-10-020', 'Payroll & Related Expenses (*)', 'asset'),
    (v_org_id, '1-4-10-030', 'System Subscribe', 'asset'),
    (v_org_id, '1-4-10-040', 'Equipment & Machine Insurance', 'asset'),
    (v_org_id, '1-4-10-050', 'Rent & Occupancy Expense', 'asset'),
    (v_org_id, '1-4-10-060', 'Consultant Fee', 'asset'),
    (v_org_id, '1-4-10-070', 'Prepaid Taxes (*)', 'asset'),
    (v_org_id, '1-4-10-080', 'Miscellaneous Prepaid Expenses', 'asset'),
    (v_org_id, '1-5-00-000', 'OTHERS CURRENT ASSETS', 'asset'),
    (v_org_id, '1-5-10-000', 'OTHERS CURRENT ASSETS (-)', 'asset'),
    (v_org_id, '1-5-10-010', 'Barter Agreement', 'asset'),
    (v_org_id, '1-5-10-020', 'Deposit on Event (*)', 'asset'),
    (v_org_id, '1-5-10-030', 'Deposit on Purchase Contract', 'asset'),
    (v_org_id, '1-5-10-040', 'Travelling Expenses - Advance', 'asset'),
    (v_org_id, '1-5-10-050', 'Current Assets - Other', 'asset'),
    (v_org_id, '1-6-00-000', 'FIXED ASSETS', 'asset'),
    (v_org_id, '1-6-10-000', 'LAND Asset', 'asset'),
    (v_org_id, '1-6-10-010', 'Land', 'asset'),
    (v_org_id, '1-6-20-000', 'BUILDING Assets', 'asset'),
    (v_org_id, '1-6-20-010', 'Building', 'asset'),
    (v_org_id, '1-6-20-020', 'Building Improvement', 'asset'),
    (v_org_id, '1-6-30-000', 'FURNITURE, FIXTURE & EQUIPMENT (FFE)', 'asset'),
    (v_org_id, '1-6-30-010', 'Furniture', 'asset'),
    (v_org_id, '1-6-30-020', 'Fixture', 'asset'),
    (v_org_id, '1-6-30-030', 'Equipment Gol I', 'asset'),
    (v_org_id, '1-6-30-040', 'Equipment Gol II', 'asset'),
    (v_org_id, '1-6-60-000', 'OPERATING UTENSIL & EQUIPMENT', 'asset'),
    (v_org_id, '1-6-60-010', 'FOH Utensil', 'asset'),
    (v_org_id, '1-6-60-020', 'Kitchen Tool & Utensil', 'asset'),
    (v_org_id, '1-6-60-030', 'Back Of Office Tool', 'asset'),
    (v_org_id, '1-6-60-040', 'Chinaware,Glassware,Silverware', 'asset'),
    (v_org_id, '1-6-60-050', 'Human Capital Item', 'asset'),
    (v_org_id, '1-6-60-060', 'Beginning Purchase', 'asset'),
    (v_org_id, '1-7-00-000', 'OTHER FIXED ASSETS', 'asset'),
    (v_org_id, '1-7-10-000', 'OTHER FIXED ASSETS :', 'asset'),
    (v_org_id, '1-7-10-010', 'Other Fixed Assets - Organization Cost / Goodwill (*)', 'asset'),
    (v_org_id, '1-7-10-020', 'Grand Opening Expenses', 'asset'),
    (v_org_id, '1-7-10-030', 'Other Fixed Assets - Pre Opening Expenses', 'asset'),
    (v_org_id, '1-7-10-040', 'Assests In Transit', 'asset'),
    (v_org_id, '2-0-00-000', 'LIABILITIES', 'liability'),
    (v_org_id, '2-1-00-000', 'CURRENT LIABILITIES', 'liability'),
    (v_org_id, '2-1-10-000', 'TRADE CREDITOR', 'liability'),
    (v_org_id, '2-1-10-010', 'AP - Raw Material & Supplies', 'liability'),
    (v_org_id, '2-1-10-020', 'AP - Utility', 'liability'),
    (v_org_id, '2-1-10-030', 'AP - Suspense', 'liability'),
    (v_org_id, '2-1-10-040', 'AP - Other', 'liability'),
    (v_org_id, '2-1-20-000', 'TRADE TAXED', 'liability'),
    (v_org_id, '2-1-20-010', 'Tax - Pembangunan I (11%)', 'liability'),
    (v_org_id, '2-1-20-020', 'Tax - PPh 21', 'liability'),
    (v_org_id, '2-1-20-030', 'Tax - PPh 21 Kas Negara', 'liability'),
    (v_org_id, '2-1-20-040', 'PPN Keluaran (Output VAT)', 'liability'),
    (v_org_id, '2-1-30-000', 'TRADE OTHER', 'liability'),
    (v_org_id, '2-1-30-010', 'Service Charge (7%)', 'liability'),
    (v_org_id, '2-1-30-020', 'BPJS Ketenagakerjaan', 'liability'),
    (v_org_id, '2-1-30-030', 'BPJS Kesehatan', 'liability'),
    (v_org_id, '2-1-30-040', 'Consigment', 'liability'),
    (v_org_id, '2-1-30-050', 'Lost and Breakage Fund', 'liability'),
    (v_org_id, '2-1-30-060', 'Trade Other - Other', 'liability'),
    (v_org_id, '2-1-40-000', 'ACCRUED EXPENSES', 'liability'),
    (v_org_id, '2-1-40-010', 'A/E - Payroll & Related', 'liability'),
    (v_org_id, '2-2-00-000', 'LONG TERM LIABILITIES', 'liability'),
    (v_org_id, '2-2-10-000', 'SHORT TERM LIABILITIES', 'liability'),
    (v_org_id, '2-2-10-010', 'Bank Loan (Short Term)', 'liability'),
    (v_org_id, '2-2-10-020', 'Financial Institution (Non Bank) Loan (Short', 'liability'),
    (v_org_id, '2-2-10-030', 'Bank Loan (Long Term / Due in This Year)', 'liability'),
    (v_org_id, '2-2-10-040', 'Financial Institution Loan (Long Term / Due i', 'liability'),
    (v_org_id, '2-2-20-000', 'NOTES PAYABLE', 'liability'),
    (v_org_id, '2-2-20-010', 'Leasing Agreement', 'liability'),
    (v_org_id, '2-2-20-020', 'Promisory Not', 'liability'),
    (v_org_id, '2-2-20-030', 'Release Payment Account', 'liability'),
    (v_org_id, '2-2-30-000', 'LONG TERM LOAN', 'liability'),
    (v_org_id, '2-2-30-010', 'Bank Loan', 'liability'),
    (v_org_id, '2-2-30-020', 'Long Term Notes Payable', 'liability'),
    (v_org_id, '2-2-30-030', 'Long Term Loan - Other', 'liability'),
    (v_org_id, '3-0-00-000', 'CAPITAL', 'equity'),
    (v_org_id, '3-1-00-000', 'OTHER CAPITAL', 'equity'),
    (v_org_id, '3-1-10-000', 'Capital(-)', 'equity'),
    (v_org_id, '3-1-10-010', 'Capital Share', 'equity'),
    (v_org_id, '3-1-10-020', 'Retained Earning Beg. Year', 'equity'),
    (v_org_id, '3-1-10-030', 'Retained Earning', 'equity'),
    (v_org_id, '3-1-10-040', 'Retained Earning - TA', 'equity'),
    (v_org_id, '3-1-10-050', 'Profit & Loss Current Year', 'equity'),
    (v_org_id, '3-1-10-060', 'Paid Up Capital', 'equity'),
    (v_org_id, '3-1-10-070', 'Owner Withdrawal', 'equity'),
    (v_org_id, '3-1-10-080', 'Balance Forward', 'equity'),
    (v_org_id, '4-0-00-000', 'REVENUES', 'income'),
    (v_org_id, '4-1-00-000', 'FOOD & BEVERAGE REVENUE', 'income'),
    (v_org_id, '4-1-00-010', 'Food Revenue', 'income'),
    (v_org_id, '4-1-00-020', 'Beverage Revenue', 'income'),
    (v_org_id, '4-1-00-030', 'Traditional Cake, Bakery, Pastry & Lite Bite Revenue', 'income'),
    (v_org_id, '4-2-00-000', 'OTHER REVENUES', 'income'),
    (v_org_id, '4-2-00-010', 'Catering Outside', 'income'),
    (v_org_id, '4-2-00-020', 'Event', 'income'),
    (v_org_id, '4-2-00-030', 'Merchandise', 'income'),
    (v_org_id, '4-2-00-040', 'Miscellaneous (Other)', 'income'),
    (v_org_id, '5-0-00-000', 'COST OF GOODS SOLD', 'expense'),
    (v_org_id, '5-1-00-000', 'COGS FOOD', 'expense'),
    (v_org_id, '5-1-10-000', 'COST OF FOOD', 'expense'),
    (v_org_id, '5-1-10-010', 'Cost of Food Raw Material', 'expense'),
    (v_org_id, '5-1-10-020', 'Cost of WIP', 'expense'),
    (v_org_id, '5-1-10-030', 'Cost of Food Spoil / Waste', 'expense'),
    (v_org_id, '5-1-20-000', 'COST OF TRADITIONAL CAKE, BAKERY, PASTRY & LITE BITE', 'expense'),
    (v_org_id, '5-1-20-010', 'Cost of TBP&L Raw Material', 'expense'),
    (v_org_id, '5-1-20-020', 'Cost of WIP', 'expense'),
    (v_org_id, '5-2-00-000', 'COGS OF BEVERAGE', 'expense'),
    (v_org_id, '5-2-00-010', 'Cost of Bev Raw Material', 'expense'),
    (v_org_id, '5-2-00-020', 'Cost of Bev RTD', 'expense'),
    (v_org_id, '5-2-00-030', 'Cost of Bev WIP', 'expense'),
    (v_org_id, '5-2-00-040', 'Cost of Bev Spoil / Waste', 'expense'),
    (v_org_id, '5-3-00-000', 'COGS OTHER REVENUES', 'expense'),
    (v_org_id, '5-3-00-010', 'Cost of Catering Outside', 'expense'),
    (v_org_id, '5-3-00-020', 'Cost of Event', 'expense'),
    (v_org_id, '5-3-00-030', 'Cost of Merchandise', 'expense'),
    (v_org_id, '5-3-00-040', 'Cost of Miscellaneous', 'expense'),
    (v_org_id, '5-3-00-050', 'Cost of Variance', 'expense'),
    (v_org_id, '6-0-00-000', 'EXPENSES', 'expense'),
    (v_org_id, '6-1-00-000', 'SALARIES AND WAGES', 'expense'),
    (v_org_id, '6-1-00-010', 'KOH S&W', 'expense'),
    (v_org_id, '6-1-00-020', 'FOH S&W', 'expense'),
    (v_org_id, '6-1-00-030', 'Support and Marketing S&W', 'expense'),
    (v_org_id, '6-1-00-040', 'BOD S&W', 'expense'),
    (v_org_id, '6-1-00-050', 'Partners Benafit', 'expense'),
    (v_org_id, '6-2-00-000', 'SUPPLIES EXPENSES', 'expense'),
    (v_org_id, '6-2-00-010', 'Kitchen Supplies', 'expense'),
    (v_org_id, '6-2-00-020', 'Chemical, Cleaning and Sanitation Supplies', 'expense'),
    (v_org_id, '6-2-00-030', 'FOH Supplies', 'expense'),
    (v_org_id, '6-2-00-040', 'Packing Supplies', 'expense'),
    (v_org_id, '6-2-00-050', 'Office & Cashier Supplies', 'expense'),
    (v_org_id, '6-3-00-000', 'MARKETING EXPENSE', 'expense'),
    (v_org_id, '6-3-00-010', 'Marketing Production Expense', 'expense'),
    (v_org_id, '6-3-00-020', 'Marketing Entertainment Expense', 'expense'),
    (v_org_id, '6-3-00-030', 'Other Marketing Expense', 'expense'),
    (v_org_id, '6-4-00-000', 'PREMISES EXPENSE', 'expense'),
    (v_org_id, '6-4-00-010', 'Rent & Occupancy Expense', 'expense'),
    (v_org_id, '6-4-00-020', 'Repairs & Maintenance Expense', 'expense'),
    (v_org_id, '6-4-00-030', 'Cleaning, Sanitation, Security & Safety Expense', 'expense'),
    (v_org_id, '6-4-00-040', 'Electricity and Water', 'expense'),
    (v_org_id, '6-4-00-050', 'Building Tax, Other Tax, Fees & Insurance Expense', 'expense'),
    (v_org_id, '6-5-00-000', 'GENERAL EXPENSE', 'expense'),
    (v_org_id, '6-5-00-010', 'Administrative Expense', 'expense'),
    (v_org_id, '6-5-00-020', 'IT, System Subscribe & Software Expense', 'expense'),
    (v_org_id, '6-5-00-030', 'Communication and WIFI Expense', 'expense'),
    (v_org_id, '6-5-00-040', 'Research & Learning Development Expense', 'expense'),
    (v_org_id, '6-5-00-050', 'Transport & Travel Expense', 'expense'),
    (v_org_id, '6-5-00-060', 'Entertainment & Misc Expense', 'expense'),
    (v_org_id, '6-5-00-070', 'Bank Charge & MDR Expense', 'expense'),
    (v_org_id, '6-5-00-080', 'Other Expense', 'expense'),
    (v_org_id, '6-5-00-090', 'Food Cost Before Cut Off', 'expense'),
    (v_org_id, '6-5-00-100', 'Utility and Service Expense', 'expense'),
    (v_org_id, '7-0-00-000', 'FIXED CHARGE', 'expense'),
    (v_org_id, '7-1-00-000', 'DEPRECIATION EXPENSES', 'expense'),
    (v_org_id, '7-1-00-010', 'Building Assets DE', 'expense'),
    (v_org_id, '7-1-00-020', 'Furniture & Fixture Equipment  DE', 'expense'),
    (v_org_id, '7-1-00-030', 'Operating Utensil & Equipment  DE', 'expense'),
    (v_org_id, '7-1-00-040', 'Other DE', 'expense'),
    (v_org_id, '7-2-00-000', 'NON OPERATING INCOME', 'income'),
    (v_org_id, '7-2-00-010', 'Interest Earning', 'income'),
    (v_org_id, '7-2-00-020', 'Miscellaneous', 'income'),
    (v_org_id, '7-3-00-000', 'NON OPERATING EXPENSES', 'expense'),
    (v_org_id, '7-3-00-010', 'Rounding', 'expense'),
    (v_org_id, '7-3-00-020', 'Bank Interest', 'expense'),
    (v_org_id, '7-3-00-030', 'Loss On Disposal Of Asset', 'expense'),
    (v_org_id, '7-3-00-040', 'Other Non Operating Expense', 'expense');

  END IF;

  -- 5. Compute is_header / level / parent_id for the whole tree just seeded.
  PERFORM repair_coa_hierarchy(v_org_id);

  -- 6. Seed default account-role mappings so invoices can post from day one
  -- without a trip to Settings > Accounting first (template-dependent —
  -- SELECT ... WHERE code = 'X' is a no-op, not an error, if a code is
  -- missing from the chosen template).
  IF p_coa_template = 'kl' THEN
    INSERT INTO default_coa_mappings (org_id, account_role, coa_id)
    SELECT v_org_id, 'accounts_payable', id FROM chart_of_accounts WHERE org_id = v_org_id AND code = '2-1-01-001';
  ELSE
    INSERT INTO default_coa_mappings (org_id, account_role, coa_id)
    SELECT v_org_id, 'accounts_payable', id FROM chart_of_accounts WHERE org_id = v_org_id AND code = '2-1-10-010'
    UNION ALL
    SELECT v_org_id, 'freight_expense', id FROM chart_of_accounts WHERE org_id = v_org_id AND code = '6-5-00-050'
    UNION ALL
    SELECT v_org_id, 'ppn_masukan', id FROM chart_of_accounts WHERE org_id = v_org_id AND code = '1-2-30-020'
    UNION ALL
    SELECT v_org_id, 'ppn_keluaran', id FROM chart_of_accounts WHERE org_id = v_org_id AND code = '2-1-20-040';
  END IF;

  RETURN json_build_object('org_id', v_org_id, 'outlet_id', v_outlet_id);
END;
$$;

GRANT EXECUTE ON FUNCTION public.register_new_org(UUID, TEXT, TEXT, TEXT, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.register_new_org(UUID, TEXT, TEXT, TEXT, TEXT) TO anon;
